server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: user-router1
          uri:  http://localhost:8300
          predicates:
            - Path=/consumer/user/**

        - id: user-router2
          uri:  http://localhost:8300
          predicates:
            - Path=/consumer/feign/user/**
