server:
  port: 8300

spring:
  application:
    name: nacos-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user: http://nacos-user-provider

logging:
  level:
    com.consumer.service.UserFeignService: debug
